source 'https://api.berkshelf.com'

cookbook 'apache2', :github => 'onehealth-cookbooks/apache2', :ref => 'COOK-3900'
cookbook 'build-essential'
cookbook 'git', :github => 'opscode-cookbooks/git'
cookbook 'mysql', :github => 'ryandub/mysql', :ref => 'debian6_apparmor'
cookbook 'ohai_plugins_test', :path => 'cookbooks/ohai_plugins_test'
cookbook 'unattended-upgrades', :github => 'firstbanco/chef-unattended-upgrades'
cookbook 'yum', :github => 'opscode-cookbooks/yum'
cookbook 'yum-cron', :github => 'poppen/yumcron-cookbook'
cookbook 'yum-epel', :github => 'opscode-cookbooks/yum-epel'
