source 'https://api.berkshelf.com'

cookbook 'apache2', :github => 'onehealth-cookbooks/apache2', :ref => 'COOK-3900'
cookbook 'build-essential'
cookbook 'git', :github => 'opscode-cookbooks/git'
cookbook 'mysql', :github => 'opscode-cookbooks/mysql', :ref => 'v5.3.6'
cookbook 'ohai_plugins_test', :path => 'cookbooks/ohai_plugins_test'
cookbook 'chef-unattended-upgrades', :github => 'firstbanco/chef-unattended-upgrades'
cookbook 'hostsfile', :github => 'customink-webops/hostsfile'
cookbook 'wordpress', :github => 'opscode-cookbooks/wordpress'
cookbook 'yum', :github => 'opscode-cookbooks/yum'
cookbook 'yum-cron', :github => 'poppen/yumcron-cookbook'
cookbook 'yum-epel', :github => 'opscode-cookbooks/yum-epel'
